apiVersion: skaffold/v4beta6
kind: Config
build:
  local:
    push: true
  artifacts:
    - image: quebecnova/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: quebecnova/tickets
      context: tickets
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: quebecnova/orders
      context: orders
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: quebecnova/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: quebecnova/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: quebecnova/client
      context: client
      sync:
        manual:
          - src: '**/*.js*'
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*